[package]
name = "sqlite"
version = "0.2.2"
description = "SQLite is a C-language library that implements a small, fast, self-contained, high-reliability, full-featured, SQL database engine"
readme = "README.md"
repository = "https://github.com/wapm-packages/sqlite"

[[module]]
name = "sqlite"
source = "build/sqlite.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.0.0-unstable"

[[command]]
name = "sqlite"
module = "sqlite"

[[command]]
name = "sqlite3"
module = "sqlite"
