# Use a base image with the desired Linux distribution
FROM ubuntu:latest

# Install necessary dependencies
RUN apt-get update && apt-get install -y curl
RUN apt-get install xz-utils

# Download and install Wasmtime
RUN curl https://wasmtime.dev/install.sh -sSf | bash


# Add Wasmtime binaries to the system PATH
ENV PATH="/root/.wasmtime/bin:$PATH"
#ENV export PATH="/root/.wasmtime/bin/wasmtime:${PATH}"

# Print Wasmtime version
# CMD ["wasmtime", "--version"]

# Copy project file
COPY ./* ./

# Run the program
CMD ["wasmtime", "run", "wasm32-wasi/release/fibo-rust.wasm"]
